# Taken from https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions
# and https://github.com/dependabot/fetch-metadata/blob/06ea45a2e4582d87b11f03c7ce596ae3261f39f6/README.md?plain=1#L133-L160
name: Dependabot auto-merge

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    uses: typisttech/.github/.github/workflows/dependabot-auto-merge.yml@v1
    with:
      minor: true
      patch: true
